### ISSUE TITLE
Error when using tiered pricing

### ISSUE THREAD

**Issue by jwpadgett** [organicinternet/magento-configurable-simple#1]
<b>Environment:</b>
Magento version: 1.3.2.1
Module changes mentioned by author on thread ( http://www.magentocommerce.com/boards/viewthread/37312/ ) have also made.

<b>Circumstances of Error:</b>
I set up a single sku with tiered pricing, within a configurable product, and received the following error:

<pre>
Notice: Undefined index:  website_price  in /Users/jason/Sites/magento/app/code/core/Mage/Catalog/Model/Product/Type/Price.php on line 216
Trace:
#0 /Users/jason/Sites/magento/app/code/core/Mage/Catalog/Model/Product/Type/Price.php(216): mageCoreErrorHandler(8, 'Undefined index...', '/Users/jason/Si...', 216, Array)
#1 /Users/jason/Sites/magento/app/code/core/Mage/Catalog/Model/Product.php(582): Mage_Catalog_Model_Product_Type_Price->getFormatedTierPrice(NULL, Object(OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product))
#2 /Users/jason/Sites/magento/app/code/core/Mage/Catalog/Block/Product/Abstract.php(235): Mage_Catalog_Model_Product->getFormatedTierPrice()
#3 /Users/jason/Sites/magento/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Block/Product/View/Type/Configurable.php(19): Mage_Catalog_Block_Product_Abstract->getTierPrices(Object(OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product))
#4 /Users/jason/Sites/magento/app/design/frontend/default/default/template/catalog/product/view/type/options/configurable.phtml(44): OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Type_Configurable->getJsonConfig()
#5 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(144): include('/Users/jason/Si...')
#6 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(176): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#7 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(193): Mage_Core_Block_Template->renderView()
#8 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Template->_toHtml()
#9 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(503): Mage_Core_Block_Abstract->toHtml()
#10 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(450): Mage_Core_Block_Abstract->_getChildHtml('options_configu...', true)
#11 /Users/jason/Sites/magento/app/design/frontend/default/default/template/catalog/product/view/options/wrapper.phtml(29): Mage_Core_Block_Abstract->getChildHtml('', true, true)
#12 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(144): include('/Users/jason/Si...')
#13 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(176): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#14 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(193): Mage_Core_Block_Template->renderView()
#15 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Template->_toHtml()
#16 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(503): Mage_Core_Block_Abstract->toHtml()
#17 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(450): Mage_Core_Block_Abstract->_getChildHtml('product.info.op...', true)
#18 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(467): Mage_Core_Block_Abstract->getChildHtml('', true, true)
#19 /Users/jason/Sites/magento/app/design/frontend/default/default/template/catalog/product/view.phtml(94): Mage_Core_Block_Abstract->getChildChildHtml('container1', '', true, true)
#20 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(144): include('/Users/jason/Si...')
#21 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(176): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#22 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(193): Mage_Core_Block_Template->renderView()
#23 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Template->_toHtml()
#24 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#25 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Text_List->_toHtml()
#26 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(503): Mage_Core_Block_Abstract->toHtml()
#27 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(454): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#28 /Users/jason/Sites/magento/app/design/frontend/default/default/template/page/2columns-right.phtml(56): Mage_Core_Block_Abstract->getChildHtml('content')
#29 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(144): include('/Users/jason/Si...')
#30 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(176): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#31 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Template.php(193): Mage_Core_Block_Template->renderView()
#32 /Users/jason/Sites/magento/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Template->_toHtml()
#33 /Users/jason/Sites/magento/app/code/core/Mage/Core/Model/Layout.php(526): Mage_Core_Block_Abstract->toHtml()
#34 /Users/jason/Sites/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(347): Mage_Core_Model_Layout->getOutput()
#35 /Users/jason/Sites/magento/app/code/core/Mage/Catalog/controllers/ProductController.php(153): Mage_Core_Controller_Varien_Action->renderLayout()
#36 /Users/jason/Sites/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(376): Mage_Catalog_ProductController->viewAction()
#37 /Users/jason/Sites/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(248): Mage_Core_Controller_Varien_Action->dispatch('view')
#38 /Users/jason/Sites/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(158): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#39 /Users/jason/Sites/magento/app/Mage.php(459): Mage_Core_Controller_Varien_Front->dispatch()
#40 /Users/jason/Sites/magento/index.php(65): Mage::run()
#41 {main}
</pre>

**Comment by jwpadgett** [comment]
This seems to be a magento error. See thread.
http://www.magentocommerce.com/boards/viewthread/44188/#t143740
