### ISSUE TITLE
Product Prices won't reindex

### ISSUE THREAD

**Issue by jsypolt** [organicinternet/magento-configurable-simple#108]
Installed version 0.8.2 on Magento CE 1.6.2 which has some existing simple and configurable products. The Product Prices index will no longer reindex. From exception.log:

2012-09-23T01:02:25+00:00 DEBUG (7): Exception message: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1
Trace: #0 /var/www/devsite/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/devsite/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /var/www/devsite/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /var/www/devsite/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array)
#4 /var/www/devsite/lib/Varien/Db/Adapter/Pdo/Mysql.php(389): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ca...', Array)
#5 /var/www/devsite/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php(140): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ca...')
#6 /var/www/devsite/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price/Configurable.php(48): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Resource_Eav_Mysql4_Product_Indexer_Price_Configurable->_prepareFinalPriceData()
#7 /var/www/devsite/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price.php(381): Mage_Catalog_Model_Resource_Product_Indexer_Price_Configurable->reindexAll()
#8 /var/www/devsite/app/code/core/Mage/Index/Model/Indexer/Abstract.php(143): Mage_Catalog_Model_Resource_Product_Indexer_Price->reindexAll()
#9 /var/www/devsite/app/code/core/Mage/Index/Model/Process.php(207): Mage_Index_Model_Indexer_Abstract->reindexAll()
#10 /var/www/devsite/app/code/core/Mage/Index/Model/Process.php(253): Mage_Index_Model_Process->reindexAll()
#11 /var/www/devsite/app/code/core/Mage/Index/controllers/Adminhtml/ProcessController.php(180): Mage_Index_Model_Process->reindexEverything()
#12 /var/www/devsite/app/code/core/Mage/Core/Controller/Varien/Action.php(420): Mage_Index_Adminhtml_ProcessController->massReindexAction()
#13 /var/www/devsite/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('massReindex')
#14 /var/www/devsite/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 /var/www/devsite/app/code/core/Mage/Core/Model/App.php(349): Mage_Core_Controller_Varien_Front->dispatch()
#16 /var/www/devsite/app/Mage.php(640): Mage_Core_Model_App->run(Array)
#17 /var/www/devsite/index.php(80): Mage::run('', 'store')
#18 {main}

**Comment by jsypolt** [comment]
Using the previous version of Configurable.php in Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price seems to fix the problem.

**Comment by raviramjit** [comment]
I have the same issue. Do you mean save the old (before install) configurable.php and after installation replace the new one?

Thanks

**Comment by pandeo** [comment]
You can download all version from here, and after replace with old one. 
But seems that problem is only in multi store websites

**Comment by raviramjit** [comment]
Not sure what you mean. I downloaded the extension from your site or are
you talking about configurable.php?

Thanks

**Comment by jsypolt** [comment]
Get the version of Configurable.php from 2010 here if you are having trouble getting this to work on Magento 1.6.
https://github.com/organicinternet/magento-configurable-simple/blob/4d9cbe81be103c12b2e478811281395748e32fc3/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php

The latest commit fixed a compatibility problem with 1.7 but it also broke the price indexer in 1.6

**Comment by raviramjit** [comment]
When I add products, still I get same error and none of the new products appear on the frontend.

Thanks,

**Comment by raviramjit** [comment]
Hello, I am running 1.7 and anytime I install this, it breaks the indexer. Can someone help me with a fix? Thanks.

**Comment by eri26** [comment]
I am running 1.9 is replacing the configurable.php file still the way to correct this?
