### ISSUE TITLE
 (OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product) with the same id

### ISSUE THREAD

**Issue by pandeo** [organicinternet/magento-configurable-simple#109]
Hello
No idea where it come from, but meybe anyone got an idea how to fix that?
Geting much report on items

a:5:{i:0;s:109:"Item (OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product) with the same id "4520" already exist";i:1;s:4859:"#0 /home6/WebsiteName/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(265): Varien_Data_Collection->addItem(Object(OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product))
#1 /home6/WebsiteName/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1055): Mage_Eav_Model_Entity_Collection_Abstract->addItem(Object(OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product))
#2 /home6/WebsiteName/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(869): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#3 /home6/WebsiteName/public_html/app/code/core/Mage/Review/Model/Observer.php(78): Mage_Eav_Model_Entity_Collection_Abstract->load()
#4 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Model/App.php(1303): Mage_Review_Model_Observer->catalogBlockProductCollectionBeforeToHtml(Object(Varien_Event_Observer))
#5 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Model/App.php(1278): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Review_Model_Observer), 'catalogBlockPro...', Object(Varien_Event_Observer))
#6 /home6/WebsiteName/public_html/app/Mage.php(431): Mage_Core_Model_App->dispatchEvent('catalog_block_p...', Array)
#7 /home6/WebsiteName/public_html/app/code/core/Mage/Catalog/Block/Product/List.php(163): Mage::dispatchEvent('catalog_block_p...', Array)
#8 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Abstract.php(862): Mage_Catalog_Block_Product_List->_beforeToHtml()
#9 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Abstract.php(582): Mage_Core_Block_Abstract->toHtml()
#10 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Abstract.php(526): Mage_Core_Block_Abstract->_getChildHtml('product_list', true)
#11 /home6/WebsiteName/public_html/app/code/core/Mage/Catalog/Block/Category/View.php(85): Mage_Core_Block_Abstract->getChildHtml('product_list')
#12 /home6/WebsiteName/public_html/app/design/frontend/galacampstore/default/template/catalog/category/view.phtml(86): Mage_Catalog_Block_Category_View->getProductListHtml()
#13 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home6/WebsiteName...')
#14 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/galaca...')
#15 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#16 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Template->_toHtml()
#17 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#18 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Text_List->_toHtml()
#19 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Abstract.php(582): Mage_Core_Block_Abstract->toHtml()
#20 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Abstract.php(526): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#21 /home6/WebsiteName/public_html/app/design/frontend/galacampstore/default/template/page/2columns-left.phtml(50): Mage_Core_Block_Abstract->getChildHtml('content')
#22 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home6/WebsiteName...')
#23 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/galaca...')
#24 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#25 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Template->_toHtml()
#26 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Model/Layout.php(529): Mage_Core_Block_Abstract->toHtml()
#27 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(391): Mage_Core_Model_Layout->getOutput()
#28 /home6/WebsiteName/public_html/app/code/core/Mage/Catalog/controllers/CategoryController.php(159): Mage_Core_Controller_Varien_Action->renderLayout()
#29 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(420): Mage_Catalog_CategoryController->viewAction()
#30 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('view')
#31 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#32 /home6/WebsiteName/public_html/app/code/core/Mage/Core/Model/App.php(349): Mage_Core_Controller_Varien_Front->dispatch()
#33 /home6/WebsiteName/public_html/app/Mage.php(655): Mage_Core_Model_App->run(Array)
#34 /home6/WebsiteName/public_html/buybestscuba.com/index.php(80): Mage::run('scuba', 'website')
#35 {main}";s:3:"url";s:68:"/index.php/diving-gear/safety.html?dir=asc&order=cycle_brand&stock=0";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"en";}

**Comment by mediarox** [comment]
Same here.

**Comment by onepack** [comment]
I have the exact same issue here in an upgraded Magento shop 1.5 to 1.7.
I applied the index fix but now this one started appearing as from today.
Will have a look into it as there is no fix yet.

**Comment by onepack** [comment]
Arg.. almost all config items give this error when opening them on the frontend... Still no solution.
