### ISSUE TITLE
Cannot initialize the indexer process.

### ISSUE THREAD

**Issue by fthusa** [organicinternet/magento-configurable-simple#158]
HI, 
I have installed below extension 
http://www.magentocommerce.com/magento-connect/simple-configurable-products.html

After that can't indexing its getting following errors 

"Cannot initialize the indexer process."

Please help me to sort out this issue.

**Comment by thomich** [comment]
Traceback on reindex "Product Prices"
2013-08-15T07:54:51+00:00 DEBUG (7): Exception message: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1
Trace: #0 shop/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 shop/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 shop/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 shop/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array)
#4 shop/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`ca...', Array)
#5 shop/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php(133): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ca...')
#6 shop/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price/Configurable.php(48): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Resource_Eav_Mysql4_Product_Indexer_Price_Configurable->_prepareFinalPriceData()
#7 shop/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price.php(385): Mage_Catalog_Model_Resource_Product_Indexer_Price_Configurable->reindexAll()
#8 shop/app/code/core/Mage/Index/Model/Indexer/Abstract.php(143): Mage_Catalog_Model_Resource_Product_Indexer_Price->reindexAll()
#9 shop/app/code/core/Mage/Index/Model/Process.php(209): Mage_Index_Model_Indexer_Abstract->reindexAll()
#10 shop/app/code/core/Mage/Index/Model/Process.php(255): Mage_Index_Model_Process->reindexAll()
#11 shop/app/code/core/Mage/Index/controllers/Adminhtml/ProcessController.php(124): Mage_Index_Model_Process->reindexEverything()
#12 shop/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Index_Adminhtml_ProcessController->reindexProcessAction()  
#13 shop/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('reindexProcess')  
#14 shop/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))  
#15 shop/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()  
#16 shop/app/Mage.php(683): Mage_Core_Model_App->run(Array)  
#17 shop/index.php(106): Mage::run('', 'store')  
#18 {main}

Maybe a help to finding the problem.. seams a sql query is wrong...

regards
thomi

**Comment by optiond** [comment]
Fix is listed here:
https://github.com/organicinternet/magento-configurable-simple/pull/85
or:
https://github.com/magdev/magento-configurable-simple/blob/92250c4d332c6647e174d4ecffe0219b8043dec0/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php 

Be sure to back up before applying.

Basically replace your file with the one listed in the link

As always, back up site and DB before applying.

**Comment by harisnano** [comment]
Hi

I'm using magento 1.7 and I also installed the extension and I started to have the reindexing problem. I also applied the changes to the Configurable.php file (suggested by optiond) and it still didn't fix the problem. Right now the only way I can reindex is if I uninstall the extension, reindex and install the extension again. 

I recieve this error when I try to reindex with the extension installed and the modified configurable.php file

root@web-1 ~]# php /var/www/vhosts/cadillac/staging/shell/indexer.php reindexall
Product Attributes index was rebuilt successfully
Product Prices index process unknown error:
exception 'PDOException' with message 'SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1' in /var/www/vhosts/cadillac/staging/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/vhosts/cadillac/staging/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/vhosts/cadillac/staging/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/vhosts/cadillac/staging/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /var/www/vhosts/cadillac/staging/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#4 /var/www/vhosts/cadillac/staging/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array)
#5 /var/www/vhosts/cadillac/staging/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`ca...', Array)
#6 /var/www/vhosts/cadillac/staging/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php(133): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ca...')
#7 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price/Configurable.php(48): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Resource_Eav_Mysql4_Product_Indexer_Price_Configurable->_prepareFinalPriceData()
#8 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price.php(385): Mage_Catalog_Model_Resource_Product_Indexer_Price_Configurable->reindexAll()
#9 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Index/Model/Indexer/Abstract.php(143): Mage_Catalog_Model_Resource_Product_Indexer_Price->reindexAll()
#10 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Index/Model/Process.php(209): Mage_Index_Model_Indexer_Abstract->reindexAll()
#11 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Index/Model/Process.php(255): Mage_Index_Model_Process->reindexAll()
#12 /var/www/vhosts/cadillac/staging/shell/indexer.php(158): Mage_Index_Model_Process->reindexEverything()
#13 /var/www/vhosts/cadillac/staging/shell/indexer.php(198): Mage_Shell_Compiler->run()
#14 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1' in /var/www/vhosts/cadillac/staging/lib/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/vhosts/cadillac/staging/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/vhosts/cadillac/staging/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /var/www/vhosts/cadillac/staging/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /var/www/vhosts/cadillac/staging/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array)
#4 /var/www/vhosts/cadillac/staging/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`ca...', Array)
#5 /var/www/vhosts/cadillac/staging/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php(133): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ca...')
#6 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price/Configurable.php(48): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Resource_Eav_Mysql4_Product_Indexer_Price_Configurable->_prepareFinalPriceData()
#7 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price.php(385): Mage_Catalog_Model_Resource_Product_Indexer_Price_Configurable->reindexAll()
#8 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Index/Model/Indexer/Abstract.php(143): Mage_Catalog_Model_Resource_Product_Indexer_Price->reindexAll()
#9 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Index/Model/Process.php(209): Mage_Index_Model_Indexer_Abstract->reindexAll()
#10 /var/www/vhosts/cadillac/staging/app/code/core/Mage/Index/Model/Process.php(255): Mage_Index_Model_Process->reindexAll()
#11 /var/www/vhosts/cadillac/staging/shell/indexer.php(158): Mage_Index_Model_Process->reindexEverything()
#12 /var/www/vhosts/cadillac/staging/shell/indexer.php(198): Mage_Shell_Compiler->run()
#13 {main}

**Comment by optiond** [comment]
It looks like you are running into a different issue now. Usually that DB problem shows up after update between some version, though it is rare.

See if any of these fix it for you.

As always, back up first.
http://www.magentocommerce.com/boards/v/viewthread/298641/#t433346
http://www.magentocommerce.com/boards/viewthread/280202/
