### ISSUE TITLE
There has been an error processing your request 

### ISSUE THREAD

**Issue by grosykevin** [organicinternet/magento-configurable-simple#234]
Hello, I have a problem with the zoom on the images of the products here is what gives me my report

a:5:{i:0;s:122:"Invalid method OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media::renderCloudOptions(Array
(
)
)";i:1;s:4329:"#0 /home/hairqualkn/www/app/design/frontend/neoshop/default/template/moo/catalog/product/view/media.phtml(81): Varien_Object->__call('renderCloudOpti...', Array)
#1 /home/hairqualkn/www/app/design/frontend/neoshop/default/template/moo/catalog/product/view/media.phtml(81): OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media->renderCloudOptions()
#2 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(241): include('/home/hairqualk...')
#3 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/neosho...')
#4 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#5 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#6 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#7 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('media', true)
#8 /home/hairqualkn/www/app/design/frontend/neoshop/default/template/catalog/product/view.phtml(69): Mage_Core_Block_Abstract->getChildHtml('media')
#9 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(241): include('/home/hairqualk...')
#10 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/neosho...')
#11 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#12 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#13 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#14 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#15 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#16 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#17 /home/hairqualkn/www/app/design/frontend/neoshop/default/template/page/2columns-right.phtml(57): Mage_Core_Block_Abstract->getChildHtml('content')
#18 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(241): include('/home/hairqualk...')
#19 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/neosho...')
#20 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#21 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#22 /home/hairqualkn/www/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#23 /home/hairqualkn/www/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#24 /home/hairqualkn/www/app/code/core/Mage/Cms/Helper/Page.php(137): Mage_Core_Controller_Varien_Action->renderLayout()
#25 /home/hairqualkn/www/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'no-route')
#26 /home/hairqualkn/www/app/code/core/Mage/Cms/controllers/IndexController.php(75): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'no-route')
#27 /home/hairqualkn/www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->noRouteAction()
#28 /home/hairqualkn/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('noRoute')
#29 /home/hairqualkn/www/app/code/community/ArtsOnIT/OfflineMaintenance/Controller/Router/Standard.php(46): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#30 /home/hairqualkn/www/app/code/core/Mage/Core/Controller/Varien/Front.php(172): ArtsOnIT_OfflineMaintenance_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#31 /home/hairqualkn/www/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#32 /home/hairqualkn/www/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#33 /home/hairqualkn/www/index.php(87): Mage::run('', 'store')
#34 {main}";s:3:"url";s:28:"/body-wave-bresilien-6a.html";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"fr";}

**Comment by nhartman7** [comment]
Did you find a solution to this error?
