### ISSUE TITLE
Cannot configure product

### ISSUE THREAD

**Issue by calvinrreed** [organicinternet/magento-configurable-simple#236]
Whenever I click the 'Edit' link in the Shopping Cart for a configurable product, I receive the following error: "Cannot configure product."

Using Magento version 1.6  
Stack Trace is below

```
exception 'Mage_Core_Exception' with message 'Product is not loaded' in     /home/mydir/stage/public_html/app/code/core/Mage/Catalog/Helper/Product/View.php:123
Stack trace:
#0 /home/mydir/stage/public_html/app/code/core/Mage/Checkout/controllers/CartController.php(285): Mage_Catalog_Helper_Product_View->prepareAndRender('13160', Object(Mage_Checkout_CartController), Object(Varien_Object))
#1 /home/mydir/stage/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(420): Mage_Checkout_CartController->configureAction()
#2 /home/mydir/stage/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('configure')
#3 /home/mydir/stage/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#4 /home/mydir/stage/public_html/app/code/core/Mage/Core/Model/App.php(349): Mage_Core_Controller_Varien_Front->dispatch()
#5 /home/mydir/stage/public_html/app/Mage.php(640): Mage_Core_Model_App->run(Array)
#6 /home/mydir/stage/public_html/index.php(96): Mage::run('', 'store')
#7 {main}
```

**Comment by scretchy** [comment]
Hello, i have the same error on 1.9.2.4, i have found, this is only if simple product not visible on store, because SCP will redirect to simple product to configure, any one have idea to solve this issue?
