### ISSUE TITLE
Invalid method OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product

### ISSUE THREAD

**Issue by nhartman7** [organicinternet/magento-configurable-simple#265]
Any ideas on what i can do to fix this error? I'm using Meigee Universal Theme. I fixed the Re indexing error but when ever i got to a category This error is generated. Please advise and thank you in advance. 

a:5:{i:0;s:106:"Invalid method OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product::isProductSale(Array
(
)
)";i:1;s:5548:"#0 /home/XX/magento/app/design/frontend/universal/default/template/catalog/product/product_labels.phtml(34): Varien_Object->__call('isProductSale', Array)
#1 /home/XX/magento/app/design/frontend/universal/default/template/catalog/product/product_labels.phtml(34): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product->isProductSale()
#2 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/home/XX/...')
#3 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/univer...')
#4 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#5 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#6 /home/XX/magento/app/design/frontend/universal/default/template/catalog/product/grids/default.phtml(46): Mage_Core_Block_Abstract->toHtml()
#7 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/home/XX/...')
#8 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/univer...')
#9 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#10 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#11 /home/XX/magento/app/design/frontend/universal/default/template/catalog/product/list.phtml(52): Mage_Core_Block_Abstract->toHtml()
#12 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/home/XX/...')
#13 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/univer...')
#14 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#15 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#16 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#17 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('product_list', true)
#18 /home/XX/magento/app/code/core/Mage/Catalog/Block/Category/View.php(90): Mage_Core_Block_Abstract->getChildHtml('product_list')
#19 /home/XX/magento/app/design/frontend/universal/default/template/catalog/category/view.phtml(50): Mage_Catalog_Block_Category_View->getProductListHtml()
#20 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/home/XX/...')
#21 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/univer...')
#22 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#23 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#24 /home/XX/magento/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#25 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#26 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#27 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#28 /home/XX/magento/app/design/frontend/universal/default/template/page/2columns-right.phtml(30): Mage_Core_Block_Abstract->getChildHtml('content')
#29 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/home/XX/...')
#30 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/univer...')
#31 /home/XX/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#32 /home/XX/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#33 /home/XX/magento/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#34 /home/XX/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#35 /home/XX/magento/app/code/core/Mage/Catalog/controllers/CategoryController.php(161): Mage_Core_Controller_Varien_Action->renderLayout()
#36 /home/XX/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Catalog_CategoryController->viewAction()
#37 /home/XX/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
#38 /home/XX/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#39 /home/XX/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#40 /home/XX/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#41 /home/XX/magento/index.php(83): Mage::run('', 'store')
#42 {main}";s:3:"url";s:64:"/pipe-threading/pipe-dies-and-bolt-dies/universal-pipe-dies.html";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

**Comment by nhartman7** [comment]
FYI with integrating with Meigee Universal Theme app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Product.php was changed to make it work. http://www.nextbitsgroup.com/ did the work 

ORIGIONAL Product.php

class OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product
    extends Mage_Catalog_Model_Product
{
    public function getMaxPossibleFinalPrice()
    {
        if(is_callable(array($this->getPriceModel(), 'getMaxPossibleFinalPrice'))) {
            return $this->getPriceModel()->getMaxPossibleFinalPrice($this);
        } else {
            #return $this->_getData('minimal_price');
            return parent::getMaxPrice();
        }
    }

```
public function isVisibleInSiteVisibility()
{
    #Force visible any simple products which have a parent conf product.
    #this will only apply to products which have been added to the cart
    if(is_callable(array($this->getTypeInstance(), 'hasConfigurableProductParentId'))
        && $this->getTypeInstance()->hasConfigurableProductParentId()) {
       return true;
    } else {
        return parent::isVisibleInSiteVisibility();
    }
}


public function getProductUrl($useSid = null)
{
    if(is_callable(array($this->getTypeInstance(), 'hasConfigurableProductParentId'))
        && $this->getTypeInstance()->hasConfigurableProductParentId()) {

        $confProdId = $this->getTypeInstance()->getConfigurableProductParentId();
        return Mage::getModel('catalog/product')->load($confProdId)->getProductUrl();

    } else {
        return parent::getProductUrl($useSid);
    }
}
```

}

EDITED Product.php

class OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product
    extends Meigee_Thememanager_Rewrite_Catalog_Product
{
    public function getMaxPossibleFinalPrice()
    {
        if(is_callable(array($this->getPriceModel(), 'getMaxPossibleFinalPrice'))) {
            return $this->getPriceModel()->getMaxPossibleFinalPrice($this);
        } else {
            #return $this->_getData('minimal_price');
            return parent::getMaxPrice();
        }
    }

```
public function isVisibleInSiteVisibility()
{
    #Force visible any simple products which have a parent conf product.
    #this will only apply to products which have been added to the cart
    if(is_callable(array($this->getTypeInstance(), 'hasConfigurableProductParentId'))
        && $this->getTypeInstance()->hasConfigurableProductParentId()) {
       return true;
    } else {
        return parent::isVisibleInSiteVisibility();
    }
}
```

}
