### ISSUE TITLE
scp on magento 1.6 - wont reindex

### ISSUE THREAD

**Issue by ghost** [organicinternet/magento-configurable-simple#56]
once 0.7.4 is installed on magento 1.6, every attempt to reindex results in a blank page
This is a fairly clean test install, with a themeforest template installed
once scp is uninstalled, the reindex works fine and completes successfully.

[06-Oct-2011 21:17:58] PHP Fatal error:  Call to a member function setTypeId() on a non-object in C:\Docs\Public\www\magento\includes\src\Mage_CatalogInventory_Model_Resource_Indexer_Stock.php on line 282

[06-Oct-2011 21:17:58] PHP Stack trace:

[06-Oct-2011 21:17:58] PHP   1. {main}() C:\Docs\Public\www\magento\index.php:0

[06-Oct-2011 21:17:58] PHP   2. Mage::run() C:\Docs\Public\www\magento\index.php:79

[06-Oct-2011 21:17:58] PHP   3. Mage_Core_Model_App->run() C:\Docs\Public\www\magento\app\Mage.php:640

[06-Oct-2011 21:17:58] PHP   4. Mage_Core_Controller_Varien_Front->dispatch() C:\Docs\Public\www\magento\includes\src__default.php:19601

[06-Oct-2011 21:17:58] PHP   5. Mage_Core_Controller_Varien_Router_Standard->match() C:\Docs\Public\www\magento\includes\src__default.php:17129

[06-Oct-2011 21:17:58] PHP   6. Mage_Core_Controller_Varien_Action->dispatch() C:\Docs\Public\www\magento\includes\src__default.php:17529

[06-Oct-2011 21:17:58] PHP   7. Mage_Index_Adminhtml_ProcessController->reindexProcessAction() C:\Docs\Public\www\magento\includes\src__default.php:13317

[06-Oct-2011 21:17:58] PHP   8. Mage_Index_Model_Process->reindexEverything() C:\Docs\Public\www\magento\app\code\core\Mage\Index\controllers\Adminhtml\ProcessController.php:124

[06-Oct-2011 21:17:58] PHP   9. Mage_Index_Model_Process->reindexEverything() C:\Docs\Public\www\magento\includes\src\Mage_Index_Model_Process.php:181

[06-Oct-2011 21:17:58] PHP  10. Mage_Index_Model_Process->reindexAll() C:\Docs\Public\www\magento\includes\src\Mage_Index_Model_Process.php:187

[06-Oct-2011 21:17:58] PHP  11. Mage_Index_Model_Indexer_Abstract->reindexAll() C:\Docs\Public\www\magento\includes\src\Mage_Index_Model_Process.php:159

[06-Oct-2011 21:17:58] PHP  12. Mage_CatalogInventory_Model_Resource_Indexer_Stock->reindexAll() C:\Docs\Public\www\magento\includes\src\Mage_Index_Model_Indexer_Abstract.php:125

[06-Oct-2011 21:17:58] PHP  13. Mage_CatalogInventory_Model_Resource_Indexer_Stock->_getTypeIndexers() C:\Docs\Public\www\magento\includes\src\Mage_CatalogInventory_Model_Resource_Indexer_Stock.php:256

**Comment by amenk** [comment]
I installed the module from git on a plain Magento EE 1.11.1.0. I added a configurable product and a simple product.
Then I went to Index Management -> Select All -> Reindex Data -> Submit.
No error was displayed.

**Comment by jvermolen** [comment]
Got an error to in Magento CE 1.8:

2013-11-01T14:58:28+00:00 DEBUG (7): Exception message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'inner.child_entity_id' in 'field list'
Trace: #0 lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ma...', Array)
#4 lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`ma...', Array)
#5 app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php(133): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ma...')
#6 app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price/Configurable.php(48): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Resource_Eav_Mysql4_Product_Indexer_Price_Configurable->_prepareFinalPriceData()
#7 app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price.php(385): Mage_Catalog_Model_Resource_Product_Indexer_Price_Configurable->reindexAll()
#8 app/code/core/Mage/Index/Model/Indexer/Abstract.php(143): Mage_Catalog_Model_Resource_Product_Indexer_Price->reindexAll()
#9 app/code/core/Mage/Index/Model/Process.php(210): Mage_Index_Model_Indexer_Abstract->reindexAll()
#10 app/code/core/Mage/Index/Model/Process.php(258): Mage_Index_Model_Process->reindexAll()
#11 app/code/core/Mage/Index/controllers/Adminhtml/ProcessController.php(182): Mage_Index_Model_Process->reindexEverything()
#12 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Index_Adminhtml_ProcessController->massReindexAction()
#13 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('massReindex')
#14 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#16 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#17 index.php(87): Mage::run('', 'store')
#18 {main}

It's about this line: #'child_entity_id'
