### ISSUE TITLE
Shipping quotes not available if only configurable products in cart

### ISSUE THREAD

**Issue by nbrewer** [organicinternet/magento-configurable-simple#61]
This is a weird one, and took a while to notice, we are experiencing an issue where - if you only have configurable products in your cart, shipping quotes are unavailable. Adding any simple/bundle product will make it work.. and, interestingly - if you click the 'update cart' button without even touching anything it suddenly works.  I can verify that the shipping module doesn't even run at all ( a Mage::log at line 1 doesn't log ) until another product is added - or the update cart button is pressed. If a customer does not hit update cart, then he will be unable to checkout at all (shipping is unavailable message)

I know there is probably some function not firing or erroring with config products initially. If no one knows what may cause this, does anyone know how to force the 'update cart' function to run when the cart page loads as a workaround?

**Comment by jamespaulphotography** [comment]
I've got the exact same problem using 1.7. Here is the exception.log report if it anyone knows on a solution please let us know.

2012-06-17T16:11:22+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Please specify a shipping method.' in /home2/devjames/public_html/app/Mage.php:594
Stack trace:
#0 /home2/devjames/public_html/includes/src/Mage_Sales_Model_Service_Quote.php(303): Mage::throwException('Please specify ...')
#1 /home2/devjames/public_html/includes/src/Mage_Sales_Model_Service_Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()
#2 /home2/devjames/public_html/includes/src/Mage_Sales_Model_Service_Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /home2/devjames/public_html/includes/src/Mage_Checkout_Model_Type_Onepage.php(774): Mage_Sales_Model_Service_Quote->submitAll()
#4 /home2/devjames/public_html/app/code/core/Mage/Checkout/controllers/OnepageController.php(511): Mage_Checkout_Model_Type_Onepage->saveOrder()
#5 /home2/devjames/public_html/includes/src/__default.php(13582): Mage_Checkout_OnepageController->saveOrderAction()
#6 /home2/devjames/public_html/includes/src/__default.php(17927): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#7 /home2/devjames/public_html/includes/src/__default.php(17484): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home2/devjames/public_html/includes/src/__default.php(20061): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home2/devjames/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#10 /home2/devjames/public_html/index.php(87): Mage::run('', 'store')
#11 {main}

Thanks
James
