### ISSUE TITLE
1.7.0.0 and SCP not function

### ISSUE THREAD

**Issue by leiweke** [organicinternet/magento-configurable-simple#84]
Hello Team,

i did a clean 1.7.0.0 install with sample data.

After installing the latest code the price indexer did not run "Cannot initialize the indexer process."

the exeption.log tells:
2012-04-26T19:19:31+00:00 DEBUG (7): Exception message: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1
Trace: #0 /Applications/MAMP/htdocs/1700rc/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /Applications/MAMP/htdocs/1700rc/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /Applications/MAMP/htdocs/1700rc/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /Applications/MAMP/htdocs/1700rc/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array)
#4 /Applications/MAMP/htdocs/1700rc/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ca...', Array)
#5 /Applications/MAMP/htdocs/1700rc/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php(135): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ca...')
#6 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price/Configurable.php(48): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Resource_Eav_Mysql4_Product_Indexer_Price_Configurable->_prepareFinalPriceData()
#7 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price.php(385): Mage_Catalog_Model_Resource_Product_Indexer_Price_Configurable->reindexAll()
#8 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Index/Model/Indexer/Abstract.php(143): Mage_Catalog_Model_Resource_Product_Indexer_Price->reindexAll()
#9 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Index/Model/Process.php(209): Mage_Index_Model_Indexer_Abstract->reindexAll()
#10 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Index/Model/Process.php(255): Mage_Index_Model_Process->reindexAll()
#11 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Index/controllers/Adminhtml/ProcessController.php(178): Mage_Index_Model_Process->reindexEverything()
#12 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Index_Adminhtml_ProcessController->massReindexAction()
#13 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('massReindex')
#14 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 /Applications/MAMP/htdocs/1700rc/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#16 /Applications/MAMP/htdocs/1700rc/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#17 /Applications/MAMP/htdocs/1700rc/index.php(87): Mage::run('', 'store')
#18 {main}

it looks like that the new feature of customer groups stops SCP, as i compared 
app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price.php
there is a new array like 'group_price'

I thinks that is the problem.

As i´m not deep in PHP, can someone help here to get it running with 1.7.0.0

Thanks a lot
Sebastian

**Comment by leiweke** [comment]
Fix provided here: https://github.com/organicinternet/magento-configurable-simple/pull/85
